require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
use_frameworks!

target 'Fleett' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
#  use_flipper!({ 'Flipper' => '0.74.0' })
pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'
pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'FleettTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'Fleett-tvOS' do
  # Pods for Fleett-tvOS

  target 'Fleett-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
